#!/usr/bin/env bash
#
# PAIOS fresh-machine bootstrap (macOS).
#
# Unlike `./lde.sh`, which is read-only and only *checks* prerequisites, this
# script *installs* them, then performs the reproducible project bootstrap and
# finishes by running `./lde.sh` to verify the machine is green.
#
# It is idempotent: re-running it on a configured machine is safe and fast.
#
#   scripts/bootstrap.sh            # install host tools, Node 24 (nvm), build
#   scripts/bootstrap.sh --check    # run ./lde.sh only, install nothing
#
# Authoritative inventory: docs/operations/development-environment.md

set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

CHECK_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --check) CHECK_ONLY=1 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            printf 'Unknown argument: %s (try --help)\n' "$arg" >&2
            exit 2
            ;;
    esac
done

step() { printf '\n==> %s\n' "$1"; }
info() { printf '    %s\n' "$1"; }

if [ "$CHECK_ONLY" -eq 1 ]; then
    exec ./lde.sh
fi

if [ "$(uname -s)" != "Darwin" ]; then
    info "This bootstrap targets macOS. On other platforms, install the tools in"
    info "docs/operations/development-environment.md manually, then run ./lde.sh."
    exit 1
fi

# --- 1. Homebrew -------------------------------------------------------------
step "Ensuring Homebrew is installed"
if ! command -v brew >/dev/null 2>&1; then
    info "Homebrew not found; installing (non-interactive)."
    NONINTERACTIVE=1 /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Make brew available in this shell for both Apple Silicon and Intel.
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
else
    info "Homebrew present: $(command -v brew)"
fi

# --- 2. Host tools via Brewfile ---------------------------------------------
step "Installing host tools from Brewfile"
BREW_PREFIX="$(brew --prefix)"
if [ ! -w "$BREW_PREFIX" ]; then
    info "Homebrew prefix is not writable: $BREW_PREFIX"
    info "Fix ownership once, then re-run this script:"
    info "  sudo chown -R \"$(whoami)\" \"$BREW_PREFIX\""
    exit 1
fi
brew bundle --file="$ROOT/Brewfile"

# --- 3. Node.js (pinned by .nvmrc, managed by nvm) ---------------------------
step "Ensuring Node.js $(cat "$ROOT/.nvmrc") via nvm"
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    # shellcheck disable=SC1091
    . "$NVM_DIR/nvm.sh"
    nvm install
    nvm use
    info "Active Node: $(node --version)"
else
    info "nvm not found at \$NVM_DIR ($NVM_DIR)."
    info "Install nvm (https://github.com/nvm-sh/nvm) and re-run, or install"
    info "Node $(cat "$ROOT/.nvmrc")+ another way (e.g. 'brew install node')."
    if command -v node >/dev/null 2>&1; then
        info "Current node on PATH: $(node --version)"
    fi
fi

# --- 4. Reproducible project bootstrap --------------------------------------
step "Installing pinned npm dependencies (npm ci)"
npm ci

step "Building the PAIOS CLI"
npm run build

# --- 5. Phase 2 setup reminders (no secrets, no model download) --------------
# Host tools (including ollama) are installed above via the Brewfile. The two
# Phase 2 steps below are intentionally NOT automated here: they involve secrets
# and a large model download, so they stay explicit and operator-driven.
step "Phase 2 (Telegram Daily Assistant) follow-ups"
if command -v ollama >/dev/null 2>&1; then
    info "ollama present: $(ollama --version 2>/dev/null | head -1)"
    info "Pull the Phase 2 model (exact model is in the Phase 2 ADR), e.g.:"
    info "  ollama pull <model-from-adr>"
else
    info "ollama not on PATH yet (installed via Brewfile on a full run)."
fi
if [ ! -f "$ROOT/.local/secrets.env" ]; then
    info "Create the local secrets store before running Phase 2:"
    info "  cp .env.example .local/secrets.env && chmod 600 .local/secrets.env"
    info "Fill in credentials per docs/operations/credentials.md."
else
    info "Local secrets store present: .local/secrets.env"
fi

# --- 5b. Optional developer shell helpers (no global config mutation) --------
# We never edit a developer's ~/.zshrc. We only print the opt-in line so the
# choice — and its reversal — stays in the developer's hands.
step "Optional developer shell helpers"
# Bake the Markdown render width (~70% of this machine's screen) into a
# git-ignored local override so it is stable across terminals and shell starts.
MD_WIDTH=$("$ROOT/scripts/shell/detect-md-width.sh" 2>/dev/null || echo "")
if [ -n "$MD_WIDTH" ]; then
    {
        printf '# Machine-specific PAIOS shell-helper overrides (git-ignored, autogenerated).\n'
        printf '# Markdown render width ~= 70%% of this screen, baked by detect-md-width.sh.\n'
        printf 'export PAIOS_MD_WIDTH=%s\n' "$MD_WIDTH"
    } > "$ROOT/scripts/shell/paios.local.zsh"
    info "Baked Markdown render width: ${MD_WIDTH} cols (~70% of screen) ->"
    info "  scripts/shell/paios.local.zsh (git-ignored; re-run bootstrap to refresh)."
fi
info "To render Markdown when you 'cat' a .md file (agent-safe, TTY-only),"
info "add this line to your ~/.zshrc, then open a new shell:"
info "  source \"$ROOT/scripts/shell/paios.zsh\""
info "Requires 'glow' (installed via Brewfile). Details:"
info "  docs/operations/development-environment.md"

# --- 6. Verify ---------------------------------------------------------------
step "Verifying environment (./lde.sh)"
./lde.sh
